parameters:
    mailjet.api_key: '%env(MAILJET_API_KEY)%'
    mailjet.api_secret: '%env(MAILJET_API_SECRET)%'
    mailjet.from_email: '%env(MAILJET_FROM_EMAIL)%'
    mailjet.from_name: '%env(MAILJET_FROM_NAME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\EventVoter:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: 'security.voter' }

    App\Service\NotificationService:
        arguments:
            $apiKey: '%mailjet.api_key%'
            $apiSecret: '%mailjet.api_secret%'
            $fromEmail: '%mailjet.from_email%'
            $fromName: '%mailjet.from_name%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
